Add command counting visitor
iis-powp-2023z/powp_jobs2d_projects pull request #13
Opened 2023-11-26 13:32 UTC by rfilipczak

2023-11-26 13:38 UTC, kowallus requested changes
please fix following issues

2023-11-26 13:38 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ComplexCommand.java
> +        this.iterator().forEachRemaining(command -> command.accept(commandVisitor));
remove this line

2023-11-26 13:38 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/visitor/CommandCountingVisitor.java
> +    }
here visitation of subcommands is required

2023-11-27 09:46 UTC, kowallus requested changes
Please fix iteration responsibility issue

2023-11-27 09:46 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/CommandManager.java
> +                this.iterator().forEachRemaining(command -> command.accept(commandVisitor));
iteration should be managed by visitors

2023-11-27 09:46 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ComplexCommand.java
> +        commandVisitor.visitComplexCommand(this);
overriding accept from ICompoudCommand seems premature

2023-11-27 15:37 UTC, rfilipczak commented on src/main/java/edu/kis/powp/jobs2d/command/ComplexCommand.java
> +        this.iterator().forEachRemaining(command -> command.accept(commandVisitor));
Done

2023-11-27 15:37 UTC, rfilipczak commented on src/main/java/edu/kis/powp/jobs2d/command/visitor/CommandCountingVisitor.java
> +    }
Done

2023-11-27 15:38 UTC, rfilipczak commented on src/main/java/edu/kis/powp/jobs2d/command/manager/CommandManager.java
> +                this.iterator().forEachRemaining(command -> command.accept(commandVisitor));
Done

2023-11-27 15:47 UTC, kowallus approved these changes

2023-11-28 11:42 UTC, merged

2023-11-28 11:43 UTC, kowallus commented
Note: counting visitor implementation should be stateless to provide ease of use and reliability.