Convert mouse clicks to driver calls
iis-powp-2023z/powp_jobs2d_projects pull request #8
Opened 2023-10-26 18:36 UTC by maresyp

2023-10-27 08:21 UTC, kowallus requested changes
one issue, and resolve (unnecessary) conflicts

2023-10-27 08:21 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +
unnecessary refactor of imports

2023-10-27 08:21 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +import edu.kis.powp.jobs2d.events.*;
unnecessary refactor of imports

2023-10-27 08:21 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/DrawLinesMouseListener.java
> +        this.driver = driver;
You should not store a driver but DriverManager instance. The driver can be changed inside an application, so you should always use the current version.

2023-10-27 11:06 UTC, maresyp commented
![CleanShot 2023-10-27 at 13 01 44](https://github.com/iis-powp-2023z/powp_jobs2d_projects/assets/69731851/ec38b6ea-1c7a-4685-b752-fa18d5afcdad)
![CleanShot 2023-10-27 at 13 02 09](https://github.com/iis-powp-2023z/powp_jobs2d_projects/assets/69731851/11c2a2d7-29e1-48a3-8f3c-f9961190344f)

Changes to imports were already merged on master branch, having that in mind it's either we do refactoring that's needed or we get back to the starting version.

2023-10-28 09:11 UTC, kowallus approved these changes
thank you. 

some minor issues

2023-10-28 09:11 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/DrawLinesMouseListener.java
> +        this.driver = DriverFeature.getDriverManager();
DriverManager could be injected to avoid DriverFeature dependency (although it doesn't change much in this case).

2023-10-28 09:11 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/DrawLinesMouseListener.java
> +    private final DriverManager driver;
the name 'driver' is incorrect

2023-10-28 09:14 UTC, merged

2023-10-28 09:16 UTC, kowallus commented
Conflicts should have been resolved either way. Please check if my resolution is correct. Sync all changes with your fork.